[package]
name = "traffic-replay"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fetcher"
path = "src/bin/fetcher.rs"

[[bin]]
name = "collator"
path = "src/bin/collator.rs"

[dependencies]
tokio = { version = "1.49.0", features = ["rt", "rt-multi-thread", "macros", "time"] }
chrono = { version = "0.4.43", features = ["serde"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["json", "env-filter"] }
vatsim_utils = { version = "0.6.0", default-features = false, features = ["rustls-tls"] }
geo = "0.32.0"
serde_json = "1.0.149"
serde = { version = "1.0.228", features = ["derive"] }
geojson = "0.24.2"
anyhow = "1.0.100"
figment = { version = "0.10.19", features = ["toml"] }
csv = "1.4.0"
slug = "0.1.6"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "postgres", "chrono", "json"] }
dotenvy = "0.15.7"
aws-sdk-s3 = "1.120.0"
aws-config = { version = "1.8.12", features = ["behavior-version-latest"] }
futures = "0.3"
